name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [test]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Download Unity Library
      run: |
        wget https://github.com/ThrowTheSwitch/Unity/archive/refs/heads/master.zip -O /tmp/Unity.zip
        unzip /tmp/Unity.zip -d /tmp

    - name: Build and Test with PlatformIO
      run: pio ci --project-conf=platformio.ini --board=teensy41 --lib="."
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

    - name: Generate coverage data
      run: |
        platformio test -e local-test --coverage
        mv .pio/build/local-test/coverage.info coverage.info

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
