name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Install gcovr
      run: pip install gcovr

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-

    - name: Install Teensy platform
      run: platformio platform install teensy

    - name: Run PlatformIO Tests
      run: platformio test -e ci-test

    - name: Generate coverage report
      run: gcovr -r . --xml -o coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: unittests
        name: codecov-upload
        fail_ci_if_error: true
