name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [test]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Install gcovr
      run: pip install gcovr

    - name: Download Unity Library
      run: |
        wget https://github.com/ThrowTheSwitch/Unity/archive/refs/heads/master.zip -O /tmp/Unity.zip
        unzip /tmp/Unity.zip -d /tmp

    - name: Move Unity Library
      run: mv /tmp/Unity-master /tmp/Unity

    - name: Copy unity_config.h
      run: cp test/unity_config.h /tmp/Unity/src/

    - name: Run tests on the embedded target
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: platformio remote test -e local-test -v

    - name: Generate Coverage Report
      run: gcovr -r . --xml-pretty -o coverage.xml

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
