name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          # Specify paths to include or exclude specific files/folders
          path: "."
          skip: "*.bin,*.exe,*.jpg,*.png,*.pdf,*.gif,*.svg"
